// Official permission names as the Feishu/Lark Open Platform scope list
// presents them, keyed by scope id. Shown on the recommended-permissions
// surfaces so users can cross-reference what they see in their own Feishu
// console, item for item. The friendly capability labels (e.g. "Show teammate
// names") still carry the plain-language framing in the brief/body; these are
// the formal console names only.
//
// Source: https://open.larksuite.com/document/server-docs/getting-started/scope-list
// (No "Lark" appears in any of these names — verified against the rendered list.)
export const FEISHU_OFFICIAL_SCOPE_NAMES: Record<string, string> = {
  'contact:user.basic_profile:readonly': "Get user's basic info",
  'contact:user.id:readonly': 'Obtain user ID via email or mobile number',
  'contact:user.employee_id:readonly': 'Obtain user ID',
  'contact:user.email:readonly': "Obtain user's email information",
  'contact:user.phone:readonly': "Obtain user's mobile number",
  'im:message.group_msg': 'Read all messages in associated group chat (sensitive scope)',
  'im:message.group_at_msg.include_bot:readonly': "Receive other bots' and users' mentions",
  'im:chat.members:write_only': 'Add and remove group member',
  'bitable:app': 'View, comment, edit and manage Base',
  'bitable:app:readonly': 'View, comment, and export Base',
  'board:whiteboard:node:create': 'Create board node',
  'board:whiteboard:node:delete': 'Delete board node',
  'board:whiteboard:node:read': 'View board node',
  'board:whiteboard:node:update': 'Update board node',
  'docs:doc': 'View, comment, edit, and manage Docs',
  'docs:doc:readonly': 'View, comment, and export Docs',
  'docs:document.comment:create': 'Add and reply to comment in document',
  'docs:document.comment:delete': 'Delete comment in document',
  'docs:document.comment:read': 'Get comments in document',
  'docs:document.comment:update': 'Modify comment in document',
  'docs:document.comment:write_only': 'Reply, edit, delete comment in document',
  'docs:document.content:read': 'View document content',
  'docs:document.media:download': 'Download image and file in document',
  'docs:document.media:upload': 'Upload image and file to document',
  'docs:document.subscription': 'Subscribe to document and update subscription status',
  'docs:document.subscription:read': 'Get subscription status of document',
  'docs:document:copy': 'Duplicate document',
  'docs:document:export': 'Export document',
  'docs:document:import': 'View and create document import task',
  'docs:event.document_deleted:read': 'Receive document delete event',
  'docs:event.document_edited:read': 'Receive document edit event',
  'docs:event.document_opened:read': 'Receive document open event',
  'docs:event:subscribe': 'Subscribe to document-related events',
  'docs:permission.member': 'View, add, update, and delete document collaborators',
  'docs:permission.member:apply': 'Request docs permission',
  'docs:permission.member:auth': "Verify user's access to document",
  'docs:permission.member:create': 'Add document collaborator',
  'docs:permission.member:delete': 'Remove document collaborator',
  'docs:permission.member:readonly': 'View document collaborators (legacy version)',
  'docs:permission.member:retrieve': 'Get document collaborators',
  'docs:permission.member:transfer': 'Transfer ownership of document',
  'docs:permission.member:update': 'Update collaborator permission of document',
  'docs:permission.setting': 'View and update document permission settings',
  'docs:permission.setting:read': 'Query permission settings of document',
  'docs:permission.setting:readonly': 'View document permission settings',
  'docs:permission.setting:write_only': 'Modify permission settings of document',
  'docs:secure_label:readonly': "View document's security level label",
  'docs:secure_label:write_only': 'Modify document security level',
  'docx:document': 'Create and edit upgraded Docs',
  'docx:document.block:convert': 'Convert text to cloud document block',
  'docx:document:create': 'Create upgraded Docs',
  'docx:document:readonly': 'View upgraded Docs',
  'docx:document:write_only': 'Edit upgraded Docs',
  'drive:drive': 'View, comment, edit, and manage all files in My Space',
  'drive:drive.metadata:readonly': 'View the metadata of files in My Space',
  'drive:drive.search:readonly': 'Search files in My Space',
  'drive:drive:readonly': 'View, comment, and download all files in My Space',
  'drive:drive:version': 'View, create, and delete document versions',
  'drive:drive:version:readonly': 'View document versions',
  'drive:export:readonly': 'Export Docs documents',
  'drive:file': 'Upload and download files to My Space',
  'drive:file.like:readonly': 'View the likes information of document',
  'drive:file.meta.sec_label.read_only': 'View document security level label',
  'drive:file:download': 'Download file in My Space',
  'drive:file:readonly': 'View and download files in My Space',
  'drive:file:upload': 'Upload file',
  'drive:file:view_record:readonly': "Get document's view history",
  'drive:quota_detail:read_one': 'Get personal storage quota information',
  'sheets:spreadsheet': 'View, comment, edit, and manage Sheets',
  'sheets:spreadsheet.meta:read': 'Query metadata of spreadsheet',
  'sheets:spreadsheet.meta:write_only': 'Modify metadata of spreadsheet',
  'sheets:spreadsheet:create': 'Create spreadsheet',
  'sheets:spreadsheet:read': 'View spreadsheet',
  'sheets:spreadsheet:readonly': 'View, comment, and export Sheets',
  'sheets:spreadsheet:write_only': 'Edit spreadsheet',
  'slides:presentation:create': 'Create slides',
  'slides:presentation:read': 'View slides',
  'slides:presentation:update': 'Edit slides',
  'slides:presentation:write_only': 'Create and edit slides',
  'space:document.event:read': 'Subscribe to file-related events under folder',
  'space:document:delete': 'Delete folder and document in My Space',
  'space:document:move': 'Move folder and document in My Space',
  'space:document:retrieve': 'Get document list in My Space folder',
  'space:document:shortcut': 'Create document shortcut',
  'space:folder:create': 'Create folder in My Space',
  'wiki:member:create': 'Add wiki space member',
  'wiki:member:retrieve': 'View wiki space member list',
  'wiki:member:update': 'Update wiki space member',
  'wiki:node:copy': 'Create wiki space node copy',
  'wiki:node:create': 'Create wiki space node',
  'wiki:node:move': 'Move wiki space node',
  'wiki:node:read': 'View wiki space node information',
  'wiki:node:retrieve': 'View wiki space node list',
  'wiki:node:update': 'Update wiki space node information',
  'wiki:setting:read': 'View wiki space settings',
  'wiki:setting:write_only': 'Update wiki space settings',
  'wiki:space:read': 'View wiki space information',
  'wiki:space:retrieve': 'View wiki space list',
  'wiki:space:write_only': 'Create and update wiki space',
  'wiki:wiki': 'View, edit, and manage Wiki',
  'wiki:wiki:readonly': 'View all Wiki',
};

// Returns the official console name for a scope, falling back to the friendly
// label if an unmapped scope ever shows up (defensive against future scopes).
export function feishuOfficialScopeName(scope: string, fallback: string): string {
  return FEISHU_OFFICIAL_SCOPE_NAMES[scope] ?? fallback;
}
